// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

public interface generateInvoiceRequestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generateInvoiceRequestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool invoiceCreated = 1;</code>
   */
  boolean getInvoiceCreated();
}
