// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

public interface generateInvoiceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:generateInvoiceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientName = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string service = 2;</code>
   */
  java.lang.String getService();
  /**
   * <code>string service = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>double amount = 3;</code>
   */
  double getAmount();
}
