// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

/**
 * Protobuf type {@code generateInvoiceRequestResponse}
 */
public  final class generateInvoiceRequestResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:generateInvoiceRequestResponse)
    generateInvoiceRequestResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use generateInvoiceRequestResponse.newBuilder() to construct.
  private generateInvoiceRequestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private generateInvoiceRequestResponse() {
    invoiceCreated_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private generateInvoiceRequestResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            invoiceCreated_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return paymentService.paymentServiceImpl.internal_static_generateInvoiceRequestResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return paymentService.paymentServiceImpl.internal_static_generateInvoiceRequestResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            paymentService.generateInvoiceRequestResponse.class, paymentService.generateInvoiceRequestResponse.Builder.class);
  }

  public static final int INVOICECREATED_FIELD_NUMBER = 1;
  private boolean invoiceCreated_;
  /**
   * <code>bool invoiceCreated = 1;</code>
   */
  public boolean getInvoiceCreated() {
    return invoiceCreated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (invoiceCreated_ != false) {
      output.writeBool(1, invoiceCreated_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (invoiceCreated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, invoiceCreated_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof paymentService.generateInvoiceRequestResponse)) {
      return super.equals(obj);
    }
    paymentService.generateInvoiceRequestResponse other = (paymentService.generateInvoiceRequestResponse) obj;

    boolean result = true;
    result = result && (getInvoiceCreated()
        == other.getInvoiceCreated());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INVOICECREATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInvoiceCreated());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static paymentService.generateInvoiceRequestResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static paymentService.generateInvoiceRequestResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static paymentService.generateInvoiceRequestResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static paymentService.generateInvoiceRequestResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(paymentService.generateInvoiceRequestResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code generateInvoiceRequestResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:generateInvoiceRequestResponse)
      paymentService.generateInvoiceRequestResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return paymentService.paymentServiceImpl.internal_static_generateInvoiceRequestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return paymentService.paymentServiceImpl.internal_static_generateInvoiceRequestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              paymentService.generateInvoiceRequestResponse.class, paymentService.generateInvoiceRequestResponse.Builder.class);
    }

    // Construct using paymentService.generateInvoiceRequestResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      invoiceCreated_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return paymentService.paymentServiceImpl.internal_static_generateInvoiceRequestResponse_descriptor;
    }

    @java.lang.Override
    public paymentService.generateInvoiceRequestResponse getDefaultInstanceForType() {
      return paymentService.generateInvoiceRequestResponse.getDefaultInstance();
    }

    @java.lang.Override
    public paymentService.generateInvoiceRequestResponse build() {
      paymentService.generateInvoiceRequestResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public paymentService.generateInvoiceRequestResponse buildPartial() {
      paymentService.generateInvoiceRequestResponse result = new paymentService.generateInvoiceRequestResponse(this);
      result.invoiceCreated_ = invoiceCreated_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof paymentService.generateInvoiceRequestResponse) {
        return mergeFrom((paymentService.generateInvoiceRequestResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(paymentService.generateInvoiceRequestResponse other) {
      if (other == paymentService.generateInvoiceRequestResponse.getDefaultInstance()) return this;
      if (other.getInvoiceCreated() != false) {
        setInvoiceCreated(other.getInvoiceCreated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      paymentService.generateInvoiceRequestResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (paymentService.generateInvoiceRequestResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean invoiceCreated_ ;
    /**
     * <code>bool invoiceCreated = 1;</code>
     */
    public boolean getInvoiceCreated() {
      return invoiceCreated_;
    }
    /**
     * <code>bool invoiceCreated = 1;</code>
     */
    public Builder setInvoiceCreated(boolean value) {
      
      invoiceCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool invoiceCreated = 1;</code>
     */
    public Builder clearInvoiceCreated() {
      
      invoiceCreated_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:generateInvoiceRequestResponse)
  }

  // @@protoc_insertion_point(class_scope:generateInvoiceRequestResponse)
  private static final paymentService.generateInvoiceRequestResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new paymentService.generateInvoiceRequestResponse();
  }

  public static paymentService.generateInvoiceRequestResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<generateInvoiceRequestResponse>
      PARSER = new com.google.protobuf.AbstractParser<generateInvoiceRequestResponse>() {
    @java.lang.Override
    public generateInvoiceRequestResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new generateInvoiceRequestResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<generateInvoiceRequestResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<generateInvoiceRequestResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public paymentService.generateInvoiceRequestResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

