// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

public interface paymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool paymentSuccessful = 1;</code>
   */
  boolean getPaymentSuccessful();

  /**
   * <code>string paymentId = 2;</code>
   */
  java.lang.String getPaymentId();
  /**
   * <code>string paymentId = 2;</code>
   */
  com.google.protobuf.ByteString
      getPaymentIdBytes();
}
