// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

public final class paymentServiceImpl {
  private paymentServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generateInvoiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generateInvoiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_generateInvoiceRequestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_generateInvoiceRequestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024paymentService.proto\"F\n\016paymentRequest" +
      "\022\020\n\010userName\030\001 \001(\t\022\016\n\006amount\030\002 \001(\001\022\022\n\nca" +
      "rdNumber\030\003 \001(\t\"?\n\017paymentResponse\022\031\n\021pay" +
      "mentSuccessful\030\001 \001(\010\022\021\n\tpaymentId\030\002 \001(\t\"" +
      ",\n\025paymentHistoryRequest\022\023\n\013patientName\030" +
      "\001 \001(\t\"P\n\026paymentHistoryResponse\022\021\n\tpayme" +
      "ntId\030\001 \001(\t\022\016\n\006amount\030\002 \001(\001\022\023\n\013paymentDat" +
      "e\030\003 \001(\t\"N\n\026generateInvoiceRequest\022\023\n\013pat" +
      "ientName\030\001 \001(\t\022\017\n\007service\030\002 \001(\t\022\016\n\006amoun" +
      "t\030\003 \001(\001\"8\n\036generateInvoiceRequestRespons" +
      "e\022\026\n\016invoiceCreated\030\001 \001(\0102\315\001\n\007payment\0220\n" +
      "\013makePayment\022\017.paymentRequest\032\020.paymentR" +
      "esponse\022C\n\016paymentHistory\022\026.paymentHisto" +
      "ryRequest\032\027.paymentHistoryResponse0\001\022K\n\017" +
      "generateInvoice\022\027.generateInvoiceRequest" +
      "\032\037.generateInvoiceRequestResponseB&\n\016pay" +
      "mentServiceB\022paymentServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_paymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_paymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentRequest_descriptor,
        new java.lang.String[] { "UserName", "Amount", "CardNumber", });
    internal_static_paymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_paymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentResponse_descriptor,
        new java.lang.String[] { "PaymentSuccessful", "PaymentId", });
    internal_static_paymentHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_paymentHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentHistoryRequest_descriptor,
        new java.lang.String[] { "PatientName", });
    internal_static_paymentHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_paymentHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentHistoryResponse_descriptor,
        new java.lang.String[] { "PaymentId", "Amount", "PaymentDate", });
    internal_static_generateInvoiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_generateInvoiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generateInvoiceRequest_descriptor,
        new java.lang.String[] { "PatientName", "Service", "Amount", });
    internal_static_generateInvoiceRequestResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_generateInvoiceRequestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_generateInvoiceRequestResponse_descriptor,
        new java.lang.String[] { "InvoiceCreated", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
