// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

public interface paymentHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientName = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();
}
