// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paymentService.proto

package paymentService;

public interface paymentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>double amount = 2;</code>
   */
  double getAmount();

  /**
   * <code>string cardNumber = 3;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string cardNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();
}
