// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingService.proto

package bookingService;

public interface appointmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appointmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientName = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string appointment_time = 2;</code>
   */
  java.lang.String getAppointmentTime();
  /**
   * <code>string appointment_time = 2;</code>
   */
  com.google.protobuf.ByteString
      getAppointmentTimeBytes();
}
