// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingService.proto

package bookingService;

public interface appointmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appointmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appointmentNumber = 1;</code>
   */
  java.lang.String getAppointmentNumber();
  /**
   * <code>string appointmentNumber = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppointmentNumberBytes();
}
