// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bookingService.proto

package bookingService;

public interface cancelAppointmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cancelAppointmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool appointmentCancelled = 1;</code>
   */
  boolean getAppointmentCancelled();
}
