// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managementService.proto

package patientManagementService;

public interface deleteRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool deleteSuccessful = 1;</code>
   */
  boolean getDeleteSuccessful();
}
