// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managementService.proto

package patientManagementService;

public interface deleteRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:deleteRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientName = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();
}
