// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managementService.proto

package patientManagementService;

public interface updateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isSuccessful = 1;</code>
   */
  boolean getIsSuccessful();
}
