// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managementService.proto

package patientManagementService;

public interface updateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:updateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientName = 1;</code>
   */
  java.lang.String getPatientName();
  /**
   * <code>string patientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string address = 2;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
